### ISSUE TITLE
Support SMART app links using the SMART on FHIR authorization model

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/legacy-sandbox#51]
#34 added preliminary support for SMART app links by appending the `iss` and `patientId` URL parameters to the launch URL. We need to add support for SMART's authorization model. This would entail not adding a `patientId` URL parameter but instead a `launch` URL parameter.

As we are allowing developers to add an arbitrary FHIR server (#19), we will need a mechanism to know if the FHIR server is protected by an authorization server honoring the SMART on FHIR authorization model and if so, the Sandbox must call an API to get a `launch` value for the given SMART app.

**Comment by jmandel** [comment]
Making this work with arbitrary fhir servers will also require that we have a well defined  way for a third party to orchestrate a launch for another app. In the smart and hspc sandboxes, we had a common convention for doing this. We exposed an oauth protected API endpoint requiring a scope called "orchestrate launch" . This endpoint takes the relevant launch context details and construct a launch token which it returns to the 3rd party. Then the 3rd party can launch another app with that token as needed. This is for testing and debugging purposes, and was not designed to support a production use case , which is consistent with how we would be using it here. We would probably want to specify this in a document on the smart website so that other sandbox servers could follow the same pattern. Until now, it has been an internal implementation detail...
