### ISSUE TITLE
Allow developers to share Sandbox configuration

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/legacy-sandbox#52]
Developers can configure a few aspects of the Sandbox today:

- CDS Services
- The FHIR server (see #19)
- Arbitrary hooks (see #26)

This configuration is stored today in a local ~~cookie~~ storage in the developer's browser. It would be nice if the developer could share this configuration with other developers or users. This would enable developers to easily share a test scenario or demo.

Another use of this feature would allow a developer to configure a scenario in the HSPC Sandbox and launch directly into the Sandbox with everyone preconfigured and ready to go.

**Comment by jmandel** [comment]
Just to clarify current behavior, I think this should say "localStorage" instead of "cookie". For the purposes of design and testing, it would be good to get to the point where all of these settings are exposed in a single local storage property, and then we can simply expose a friendly way to set and get that property (with validation when setting). If the goal is to support deep real Iraq's from an outside EHR, then we should also make sure that the current application state fields are set of all as well. For example, currently we ensure that the current hook and any relevant information like drug name can be pre-populated from the URL. We might roll that into some kind of initial state property of our configuration.

**Comment by kpshek** [comment]
Oops, I did mean localStorage instead of cookie. I'll chalk that up to logging this in the middle of the night. 😄 

And yes, the intention is to support deep linking in to the Sandbox.

**Comment by kpshek** [comment]
Closing out graveyard issues on the deprecated legacy Sandbox. If this issue is still desired, please log an issue against our new [sandbox](https://github.com/cds-hooks/sandbox/issues).
