### ISSUE TITLE
Card's link URL gets duplicate parameters on service change

### ISSUE THREAD

**Issue by agrishkan** [cds-hooks/legacy-sandbox#80]
Steps to reproduce:
- add a cds service that returns a card with an link
- switch entries in the Select a Service drop-down on the right, in the CDS Service Exchange section
- see the link URL in the card get multiple duplicates of fhirServiceUrl and patient parameters

**Comment by zplata** [comment]
@agrishkan Thanks for reporting this! This issue is known and should be addressed in a solution we have for [this issue](https://github.com/cds-hooks/sandbox/issues/51), which should have a PR going out soon enough. We'll follow up on this once we merge a fix for this defect in to see if you still come across this.

**Comment by zplata** [comment]
@agrishkan A fix for this issue has been deployed. Let me know if you're still seeing the issue on your end.

**Comment by agrishkan** [comment]
No longer seeing the bug.
